### ISSUE TITLE
ImportError: No module named model_libs

### ISSUE THREAD

**Issue by JunxiangWang** [yuantailing/ctw-baseline#12]
我尝试在caffe下训练一个模型，发生了这个错误
python train.py 
python2 ssd_hardcode/ssd_pascal_512.py
Traceback (most recent call last):
  File "ssd_hardcode/ssd_pascal_512.py", line 3, in <module>
    from caffe.model_libs import *
ImportError: No module named model_libs
Traceback (most recent call last):
  File "train.py", line 35, in <module>
    main()
  File "train.py", line 31, in main
    assert 0 == p.returncode
AssertionError

**Comment by yuantailing** [comment]
Did you build pycaffe correctly?

```
cd caffe && cp Makefile.config.example Makefile.config && make -j8 && make py
```

**Comment by yuantailing** [comment]
Sorry, I clicked `Close issue` accidentally.

**Comment by JunxiangWang** [comment]
I built paycaffe correctly and added PYTHONPATH into the file of~/.bashrc,but there was the same error

**Comment by yuantailing** [comment]
Maybe you are at a wrong branch. Try

`cd ssd/caffe && checkout b4bacbbdc40945c6c91d29c10003b0057a54e70c`

**Comment by gangliu123** [comment]
@yuantailing 
I got the same issue. And I tried that, it doesn't work

**Comment by yuantailing** [comment]
What's output of `ls ssd/caffe/python/caffe` and `cd ssd/caffe && git status`?
