### ISSUE TITLE
issue when run prepare_test

### ISSUE THREAD

**Issue by gangliu123** [yuantailing/ctw-baseline#13]
Hi, I got some error when I try to get test.txt by running prepare_test file. Could you give me some help? Thanks a lot.

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/deeplearn/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/deeplearn/anaconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/gangliu/ctw-baseline/ssd/pythonapi/common_tools.py", line 77, in parallel_work
    func(*args_list[i], tid=tid)
  File "/home/gangliu/ctw-baseline/ssd/pythonapi/common_tools.py", line 92, in foo
    func(*args)
  File "../detection/prepare_test_data.py", line 77, in foo
    crop_once(*args)
  File "../detection/prepare_test_data.py", line 52, in crop_once
    assert image.shape == imshape
AttributeError: 'NoneType' object has no attribute 'shape'

list test 0 / 1

**Comment by yuantailing** [comment]
Print image file name, ensure file exists. If not, see `Download images and annotations' section in tutorial part-1.

**Comment by gangliu123** [comment]
I‘ll try it. Thank you.
